### ISSUE TITLE
Does not work ( Is64BitProcess )

### ISSUE THREAD

**Issue by MrDeej** [chingucoding/WinUI-UnitTest-Templates#1]
Hello sir!

I downloaded your template, created both of the projects, and both failed to run tests.

Log level is set to Informational (Default).
Connected to test environment '< Local Windows Environment >'
Test data store opened in 0,009 sec.
Loaded 0 test records from the solution cache in 0,133 sec.
========== Starting test discovery ==========
Could not determine target device configuration. Exception: System.Runtime.InteropServices.COMException (0x80020009): The method or operation is not implemented.
   at EnvDTE.Property.get_Value()
   at Microsoft.VisualStudio.TestWindow.ShellServices.ProjectData.<GetRemoteMachineAddressAsync>d__85.MoveNext()
[MSTest][Discovery][C:\Temp\UnitTestApp1\bin\x64\Debug\net5.0-windows10.0.19041.0\UnitTestApp1.dll] Failed to discover tests from assembly C:\Temp\UnitTestApp1\bin\x64\Debug\net5.0-windows10.0.19041.0\UnitTestApp1.dll. Reason:File does not exist: C:\Temp\UnitTestApp1\bin\x64\Debug\net5.0-windows10.0.19041.0\UnitTestApp1.dll
No test is available in C:\Temp\UnitTestApp1\bin\x64\Debug\net5.0-windows10.0.19041.0\UnitTestApp1.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
========== Test discovery finished: 0 Tests found in 2,5 sec ==========
Could not determine target device configuration. Exception: System.Runtime.InteropServices.COMException (0x80020009): The method or operation is not implemented.
   at EnvDTE.Property.get_Value()
   at Microsoft.VisualStudio.TestWindow.ShellServices.ProjectData.<GetRemoteMachineAddressAsync>d__85.MoveNext()
Could not determine target device configuration. Exception: System.Runtime.InteropServices.COMException (0x80020009): The method or operation is not implemented.
   at EnvDTE.Property.get_Value()
   at Microsoft.VisualStudio.TestWindow.ShellServices.ProjectData.<GetRemoteMachineAddressAsync>d__85.MoveNext()
========== Starting test run ==========
The active test run was aborted. Reason: Unable to communicate with test host process.
========== Test run aborted: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========
Building Test Projects
Could not determine target device configuration. Exception: System.Runtime.InteropServices.COMException (0x80020009): The method or operation is not implemented.
   at EnvDTE.Property.get_Value()
   at Microsoft.VisualStudio.TestWindow.ShellServices.ProjectData.<GetRemoteMachineAddressAsync>d__85.MoveNext()
========== Starting test run ==========
The active test run was aborted. Reason: Unable to communicate with test host process.
========== Test run aborted: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========
Could not determine target device configuration. Exception: System.Runtime.InteropServices.COMException (0x80020009): The method or operation is not implemented.
   at EnvDTE.Property.get_Value()
   at Microsoft.VisualStudio.TestWindow.ShellServices.ProjectData.<GetRemoteMachineAddressAsync>d__85.MoveNext()
========== Starting test run ==========
The active test run was aborted. Reason: Unable to communicate with test host process.
========== Test run aborted: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========
Could not determine target device configuration. Exception: System.Runtime.InteropServices.COMException (0x80020009): The method or operation is not implemented.
   at EnvDTE.Property.get_Value()
   at Microsoft.VisualStudio.TestWindow.ShellServices.ProjectData.<GetRemoteMachineAddressAsync>d__85.MoveNext()
Starting test discovery for requested test run
========== Starting test discovery ==========
========== Test discovery finished: 2 Tests found in 1,4 sec ==========
========== Starting test run ==========
========== Test run finished: 2 Tests (2 Passed, 0 Failed, 0 Skipped) run in 59 ms ==========
Could not determine target device configuration. Exception: System.Runtime.InteropServices.COMException (0x80020009): The method or operation is not implemented.
   at EnvDTE.Property.get_Value()
   at Microsoft.VisualStudio.TestWindow.ShellServices.ProjectData.<GetRemoteMachineAddressAsync>d__85.MoveNext()
No tests found to run.

**Comment by chingucoding** [comment]
Hi, can you share which versions of Visual Studio, Win APP Sdk, MSTest and Windows you are using? Currently, the templates are quite unstable especially with different versions so it could be that one of the components listed above could cause this.

**Comment by MrDeej** [comment]
I have tried a couple of different apporached, but here is the latest:

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>App2</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
    <PublishProfile>win10-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>
	  <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\SplashScreen.scale-200.png" />
    <Content Include="Assets\LockScreenLogo.scale-200.png" />
    <Content Include="Assets\Square150x150Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
    <Content Include="Assets\StoreLogo.png" />
    <Content Include="Assets\Wide310x150Logo.scale-200.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22567-preview" />
    <Manifest Include="$(ApplicationManifest)" />
	    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.7.1" />
	    <PackageReference Include="MSTest.TestAdapter" Version="2.1.1" />
	    <PackageReference Include="MSTest.TestFramework" Version="2.1.1" />
	    <PackageReference Include="coverlet.collector" Version="1.3.0" />
  </ItemGroup>
	<ItemGroup>
		<ProjectCapability Include="TestContainer" />
	</ItemGroup>
  
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnablePreviewMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
</Project>

Also, Visual studio 17.1.0

Does the templates work at your side? 

We are trying to get our azure pipeline running for WinUI components.

**Comment by chingucoding** [comment]
I can repo the test app with UI not working on my end, the non UI tests work on my machine. I'll look into this and get back to you.

**Comment by chingucoding** [comment]
@MrDeej I tried commenting out the assembly cleanup in the example unit test and the tests seemed to work. Could you try removing the assembly cleanup and see if that fixes your issue too?

**Comment by MrDeej** [comment]
What do you mean, Assembly Cleanup?

**Comment by chingucoding** [comment]
If you are using the Unit test with UI template, inside the UnitTest1.cs file, you should see a function with the `AssemblyCleanup` function. What happens if you remove it and run the tests again?

**Comment by MrDeej** [comment]
Ok, now the tests are running when I create new from template. 

But still get this: 

`PM> dotnet test
  Determining projects to restore...
  Restored C:\Temp\UnitTestApp6\UnitTestApp6.csproj (in 781 ms).
C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages\microsoft.windows.sdk.buildtools\10.0.22000.194\build\Microsoft.Windows.SDK.BuildTools.props(4,37): error MSB4185: The function "Is64BitProcess" on type "System.Environment" is not available for execution as an MSBuild property function. [C:\Temp\UnitTestApp6\UnitTestApp6.csproj]
PM> dotnet test
  Determining projects to restore...
  All projects are up-to-date for restore.
C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages\microsoft.windows.sdk.buildtools\10.0.22000.194\build\Microsoft.Windows.SDK.BuildTools.props(4,37): error MSB4185: The function "Is64BitProcess" on type "System.Environment" is not available for execution as an MSBuild property function. [C:\Temp\UnitTestApp6\UnitTestApp6.csproj]
`

**Comment by chingucoding** [comment]
From what I heard, using the dotnet CLI is not really supported right now with WinUI 3 projects so it is not really a surprise to me that this is not working as expected. As of right now, it seems that you can only use [Visual Studio to build WinUI 3 apps](https://docs.microsoft.com/windows/apps/windows-app-sdk/set-up-your-development-environment?WT.mc_id=WDIT-MVP-5004239), If using azure devops, you can probably use the VSTest step to run tests against your WinUI projects, however I have not tried that so far.

**Comment by chingucoding** [comment]
FWIW, I updated the template in the extension to not include the faulty assembly cleanup code.

**Comment by MrDeej** [comment]
You should try 1.01, and see if it is any better?

**Comment by chingucoding** [comment]
As long as the WinUI build tool chain is still tightly coupled with Visual Studio, there is not much I can do here. In my testing, I wasn't able to build a newly created WinUI 3 packaged app with `dotnet build` (received the same error message about Is64BitProcess) so I am also not expecting `dotnet test` to work. This is a WinUI issue, hence I'm closing this issue.
