### ISSUE TITLE
Does not build Test project running under Windows SDK 1.1 release

### ISSUE THREAD

**Issue by WideDopple** [chingucoding/WinUI-UnitTest-Templates#4]
Attempting to compile test project based on these templates produces the following error.
Packaged .NET applications with an app host exe cannot be ProcessorArchitecture neutral. Please specify a RuntimeIdentifier or a Platform other than AnyCPU.	C:\Users\neil\.nuget\packages\microsoft.windowsappsdk\1.1.0\buildTransitive\Microsoft.Build.Msix.Packaging.targets	1016

Fails this condition in .targets file...
 <Error Condition="'$(UseAppHost)' == 'true' and '$(_ProjectArchitectureOutput)' == 'neutral' and '$(AllowNeutralPackageWithAppHost)' != 'true'"
      Text="Packaged .NET applications with an app host exe cannot be ProcessorArchitecture neutral. Please specify a RuntimeIdentifier or a Platform other than AnyCPU." />

**Comment by chingucoding** [comment]
Version 0.3.0 was just released to the marketplace, could you see if that fixes the issue you have? If not, can you share what your project setup is?

**Comment by chingucoding** [comment]
Closing due to staleness, if you are still encountering this issue feel free to reopen this issue.
